/**
 * Narrative overviews for the 8 target districts of Odisha.
 * Numbers are sourced from MODEL_DATA, MODEL_STATS_DATA and MODEL_URBAN_RURAL_DATA
 * (WorldPop R2025A, calibrated to Census of India 2011, projected 2011-2036).
 */

export interface DistrictOverview {
  paragraphs: string[];
  highlightPhrases: string[];
}

export const DISTRICT_OVERVIEWS: Record<string, DistrictOverview> = {

  Odisha: {
    paragraphs: [
      `Odisha's population is projected to grow from 41.97 million in 2011 (Census of India) to 49.80 million by 2036, an addition of 7.83 million residents at a compound annual growth rate near 0.69%. Spread across 155,707 km², state-level density rises modestly from 270 persons per km² to about 320, well below the national average. The slow trajectory reflects Odisha's advanced position in India's demographic transition: state fertility has been at or below replacement since the late 2010s.`,
      `Year-on-year growth eases from ~0.81% in the early 2010s to ~0.61% by the mid-2030s, a faster deceleration than India overall. The headline story is structural: coastal districts (Cuttack–Khordha–Puri belt and the Ganjam–Berhampur corridor) drive most absolute growth and almost all urban-system expansion, while interior KBK and tribal districts compound more slowly, shaped by out-migration and lower fertility relative to historic norms.`,
      `Urbanisation moves from 16.69% in 2011 to 20.94% by 2036, still less than half the all-India urban share by the end of the projection. State urban population grows from ~7.0 million to ~10.4 million, an increment of 3.4 million; rural population still grows in absolute terms, by 4.4 million, mostly in the mining and tribal interior. The dual planning frame remains metropolitan in the east (Bhubaneswar–Cuttack twin city, Rourkela, Berhampur, Sambalpur) and rural-service-delivery in the south and western tribal belt.`,
    ],
    highlightPhrases: [
      '41.97 million',
      '49.80 million',
      '7.83 million',
      '0.69%',
      '155,707 km²',
      '270 persons per km²',
      '320',
      '~0.81%',
      '~0.61%',
      '~7.0 million',
      '~10.4 million',
      '3.4 million',
      '4.4 million',
      '16.69%',
      '20.94% by 2036',
    ],
  },

  Anugul: {
    paragraphs: [
      `Anugul begins the projection window with a 2011 Census population of 1.27 million and is projected to reach 1.52 million by 2036, an addition of roughly 247,000 people over 25 years at a compound annual growth rate near 0.71%. Spread over 6,375 km², the district carries a moderate population density that climbs from 200 persons per km² in 2011 to about 239 by 2036, below the state average but rising steadily.`,
      `Year-on-year growth tracks Odisha's broader trajectory of decelerating fertility: ~0.83% in the early 2010s eases to roughly 0.65% by the late 2020s. The district's economic base, Mahanadi Coalfields' Talcher complex, NTPC's thermal cluster, NALCO's aluminium smelter and downstream metallurgy, supplies the in-migration that keeps Anugul above the state median rate while still well short of the metropolitan corridors.`,
      `Urbanisation is moderate. From a 2011 urban share of 16.85% (mostly Talcher, Anugul town, and the company-town belts), the share advances ~0.17 pp/yr to about 21.1% by 2036. The urban population grows from ~215,000 in 2011 to ~321,000 in 2036; the rural population continues to grow modestly in mining peripheries before plateauing late in the period. Planning priorities visible in this trajectory: water and AQI services around the thermal cluster, in-migrant housing, and post-extraction land transition rather than headline density management.`,
    ],
    highlightPhrases: [
      '1.27 million',
      '1.52 million',
      '247,000 people',
      '0.71%',
      '6,375 km²',
      '200 persons per km²',
      '239 by 2036',
      '~0.83%',
      'roughly 0.65%',
      '16.85%',
      '21.1% by 2036',
      '~215,000',
      '~321,000',
    ],
  },

  Balangir: {
    paragraphs: [
      `Balangir's population rises from 1.65 million in 2011 to a projected 1.93 million by 2036, a net gain of about 280,000 over the period. Annual growth slows from roughly 0.76% in the early 2010s to 0.55% by the early 2030s, among the slowest in this 30-district panel. With 6,575 km², density climbs from 251 to 293 persons per km², still below the state average.`,
      `Agrarian and drought-prone, Balangir lies in the KBK belt and remains one of Odisha's most rural districts. Seasonal out-migration to Andhra Pradesh, Telangana and Chhattisgarh for brick-kiln and construction labour is well documented and is part of why the measured growth here lags the industrial-belt districts. The urban share advances modestly from 9.49% in 2011 to 13.74% by 2036.`,
      `The urban population, concentrated in Balangir town, Titilagarh, and Patnagarh, grows from ~157,000 to ~265,000 over 25 years, an increment of about 108,000. Rural population grows by a similar absolute amount but at a much slower percentage pace; the rural-urban gap narrows. Investment priorities consistent with this trajectory are irrigation expansion, micro-enterprise around the small towns, and migration-management infrastructure rather than large-scale urban build-out.`,
    ],
    highlightPhrases: [
      '1.65 million',
      '1.93 million',
      'roughly 0.76%',
      '0.55%',
      '6,575 km²',
      '293 persons per km²',
      '280,000',
      '251',
      '9.49%',
      '13.74% by 2036',
      '~157,000',
      '~265,000',
      '108,000',
    ],
  },

  Baleshwar: {
    paragraphs: [
      `Baleshwar (Balasore) starts the period with 2.32 million residents in 2011 and reaches 2.84 million by 2036, an absolute gain of about 517,000, the largest growth in the northern coastal belt. The 3,634 km² area gives an unusually high non-metropolitan density: 639 persons per km² in 2011 rising to 781 by 2036. Annual growth runs ~0.90% early and eases to ~0.76% by 2036, the highest CAGR (0.81%) of any district in this panel.`,
      `Coastal northern Odisha, Baleshwar combines a fertile rice-and-pulses agriculture base on the Subarnarekha delta, the DRDO Chandipur Integrated Test Range, small-scale industries around Balasore town, and a steady labour-out-migration link with Jamshedpur (Jharkhand) and West Bengal. The district sits in a cyclone-exposure corridor, Fani (2019) and Yaas (2021) reinforced the case for resilient infrastructure as a planning baseline.`,
      `Urbanisation moves modestly from 11.21% in 2011 to 15.46% by 2036. Urban population grows from ~260,000 to ~439,000, an increment of 179,000; rural population adds roughly twice that (339,000) in absolute terms. Balasore town and Soro lead urban growth. Strategic priorities here are coastal-cyclone resilience, port-of-Dhamra spillover effects, and managing the peri-urban Balasore–Soro corridor.`,
    ],
    highlightPhrases: [
      '2.32 million',
      '2.84 million',
      '~0.90%',
      '~0.76% by 2036',
      '0.81%',
      '3,634 km²',
      '639 persons per km²',
      '781 by 2036',
      '517,000',
      '11.21%',
      '15.46% by 2036',
      '~260,000',
      '~439,000',
      '179,000',
      '339,000',
    ],
  },

  Bargarh: {
    paragraphs: [
      `Bargarh grows from 1.48 million in 2011 to 1.74 million by 2036, an increase of about 263,000 across 5,837 km² of largely irrigated terrain. Density rises from 254 to 299 persons per km². Annual growth runs ~0.80% early, easing to ~0.57% by 2036, a typical deceleration for an irrigated-agriculture economy with stable in-migration.`,
      `Known as the "rice bowl of Odisha", Bargarh lies in the Hirakud Dam command area and produces a disproportionate share of state paddy output. Beyond agriculture, the district hosts cement clusters (UltraTech, ACC Bargarh works), handloom (Bargarh sarees), and the Sambalpuri textile cluster spilling over from Sambalpur. Padampur and Bhatli tehsils anchor small-town commerce.`,
      `Urbanisation moves from 8.18% in 2011 to 12.43% by 2036. Urban population grows from ~121,000 to ~217,000, a 96,000 increment, large relative to the 2011 baseline. Rural population still grows by 167,000, with most increment in canal-fed tehsils. Investment focus areas are irrigation-efficiency upgrades, market-yard infrastructure for paddy, and cement-cluster environmental management.`,
    ],
    highlightPhrases: [
      '1.48 million',
      '1.74 million',
      '~0.80%',
      '~0.57% by 2036',
      '5,837 km²',
      '299 persons per km²',
      '263,000',
      '254',
      '8.18%',
      '12.43% by 2036',
      '~121,000',
      '~217,000',
      '96,000',
      '167,000',
    ],
  },

  Boudh: {
    paragraphs: [
      `Baudh (Boudh) is the smallest district in Odisha by population: 441,000 in 2011 growing to 527,000 by 2036, an addition of about 86,000. Annual growth runs ~0.83% early, settling to ~0.65% by the 2030s, close to the panel mean. Across 3,098 km², density climbs from 142 to 170 persons per km², among the lowest in the state.`,
      `Carved out of undivided Phulbani in 1994, the district remains predominantly rural with forest cover above 35%. The economy is agriculture (rice, oilseeds), forest produce (mahua, kendu leaves, tasar silk) and small-trader commerce along the Tel river. Tribal communities, primarily Kondh and Kandha, constitute a sizeable share of the population and shape settlement patterns.`,
      `Urbanisation rises from a baseline 4.62% in 2011 to 8.87% by 2036. Urban population grows from ~20,000 to ~47,000, concentrated in Boudh town (the only Municipal Council). Rural population still grows by ~59,000 over the period. Strategic emphases here are tribal-area health and education, forest-livelihood support, and single-cluster small-town infrastructure rather than urban-system planning.`,
    ],
    highlightPhrases: [
      '~0.83%',
      '~0.65%',
      '3,098 km²',
      '170 persons per km²',
      '000 by 2036',
      '441,000',
      '527,000',
      '86,000',
      '142',
      '35%',
      '4.62%',
      '8.87% by 2036',
      '~20,000',
      '~47,000',
      '~59,000',
    ],
  },

  Bhadrak: {
    paragraphs: [
      `Bhadrak grows from 1.51 million in 2011 to 1.81 million by 2036, an increase of about 304,000. Across only 2,505 km², among the smallest in the state, density rises from 601 to 723 persons per km², well above the state mean. Annual growth runs ~0.83% early, easing to ~0.69% in the 2030s.`,
      `Coastal Bhadrak hosts the Tata Steel BSL (formerly Bhushan Steel & Power) complex at Meramundali, with associated downstream metal industries; proximity to Dhamra Port and the proposed petrochemical cluster brings further industrial pull. Agriculture remains the broader employment base, paddy, oilseeds, fish farming, but industry drives both density and migration. Bhadrak town and Basudevpur are the largest urban centres.`,
      `Urbanisation moves from 12.43% to 16.68% over the period. Urban population grows from ~187,000 to ~302,000; rural from 1.32M to 1.51M. Planning priorities visible in this trajectory: industrial-area environmental compliance, cyclone-resilient infrastructure (Bhadrak is in a high-exposure coastal zone), and urban-services capacity around the Bhadrak–Basudevpur corridor.`,
    ],
    highlightPhrases: [
      '1.51 million',
      '1.81 million',
      '~0.83%',
      '~0.69%',
      '2,505 km²',
      '723 persons per km²',
      '304,000',
      '601',
      '12.43%',
      '16.68%',
      '~187,000',
      '~302,000',
      '1.32M',
      '1.51M',
    ],
  },

  Cuttack: {
    paragraphs: [
      `Cuttack starts the period with the third-highest district population in this panel at 2.62 million in 2011 and reaches 3.09 million by 2036, about 466,000 additional residents on a relatively compact 3,932 km². Density climbs from 668 persons per km² to roughly 786, second only to neighbouring Khordha and well above the state mean.`,
      `Annual growth holds in the 0.7–0.9% band early in the period and eases to about 0.6% by the mid-2030s. As Odisha's historic capital and second-largest city, Cuttack benefits from the gravitational pull of the Bhubaneswar–Cuttack metropolitan region, a contiguous urban corridor along the Mahanadi delta that draws in regional migrants. The district also hosts judicial and educational institutions, the silver-filigree and textile clusters, and the SCB Medical College anchor.`,
      `Urban share moves from 27.78% in 2011 to 32.03% by 2036, well above the state mean. Urban population grows from ~729,000 in 2011 to ~990,000 by 2036, a gain of roughly 261,000. Rural blocks in the periphery, Salepur, Athagad, Banki, continue to grow but at a much slower pace than the city core.`,
      `The implication is that Cuttack remains a high-density, urbanising district where peri-urban infrastructure pressure (drainage, traffic, land conversion) dominates over headline growth concerns; twin-city coordination with Khordha is the natural planning frame.`,
    ],
    highlightPhrases: [
      '2.62 million',
      '3.09 million',
      '3,932 km²',
      '668 persons per km²',
      '466,000',
      '786',
      '0.9%',
      '0.6%',
      '27.78%',
      '32.03% by 2036',
      '000 by 2036',
      '~729,000',
      '~990,000',
      '261,000',
    ],
  },

  Deogarh: {
    paragraphs: [
      `Debagarh (Deogarh) is one of the smallest and lowest-density districts in Odisha. Population grows from 312,520 in 2011 to 373,000 by 2036, an addition of 60,000. Across 2,940 km², density rises from 106 to 127 persons per km², among the bottom three in the state. Annual growth runs ~0.82% early, easing to ~0.64%.`,
      `Carved out of Sambalpur in 1994, Debagarh is heavily forested (Pradhanpat, Kurudkut hills) with tribal Bhuiyan and Kolha communities. Iron-ore deposits in the south are being explored, but the district lacks the established mining infrastructure of Kendujhar or Sundargarh. Economic activity is agriculture, forest produce and small-trader commerce.`,
      `Urbanisation rises from 7.83% in 2011 to 12.08% by 2036. Urban population grows from ~24,000 to ~45,000, almost entirely in Debagarh town. Rural population grows by ~39,000. Strategic emphases here are forest-livelihood support, tribal-welfare service delivery, and managed mineral-resource development as exploration expands.`,
    ],
    highlightPhrases: [
      '~0.82%',
      '~0.64%',
      '2,940 km²',
      '127 persons per km²',
      '000 by 2036',
      '312,520',
      '373,000',
      '60,000',
      '106',
      '7.83%',
      '12.08% by 2036',
      '~24,000',
      '~45,000',
      '~39,000',
    ],
  },

  Dhenkanal: {
    paragraphs: [
      `Dhenkanal grows from 1.19 million in 2011 to 1.42 million by 2036, an increase of about 230,000. Across 4,452 km², density rises from 268 to 320 persons per km². Annual growth runs ~0.83% early, slowing to ~0.63% in the 2030s.`,
      `Located between Anugul and Cuttack along the Cuttack–Sambalpur railway corridor, Dhenkanal combines small-scale industries (cement, paper, food-processing), education institutions (BPUT Dhenkanal campus, the Indian Institute of Mass Communication), and the Bhuban silver-filigree cluster. Agriculture remains the largest employment sector. Kapilash and Hindola heritage sites give the district modest tourism flow.`,
      `Urbanisation moves from 9.14% to 13.39%. Urban population grows from ~109,000 to ~190,000, an 81,000 increment concentrated in Dhenkanal town and Hindol. Rural population still grows by 148,000. Planning priorities are corridor-led industrial absorption, university-town infrastructure, and water-supply augmentation for the growing urban cluster.`,
    ],
    highlightPhrases: [
      '1.19 million',
      '1.42 million',
      '~0.83%',
      '~0.63%',
      '4,452 km²',
      '320 persons per km²',
      '230,000',
      '268',
      '9.14%',
      '13.39%',
      '~109,000',
      '~190,000',
      '81,000',
      '148,000',
    ],
  },

  Gajapati: {
    paragraphs: [
      `Gajapati grows from 578,000 in 2011 to 678,000 by 2036, an addition of 100,000. Across 4,325 km² of hilly southern terrain, density rises from 134 to 157 persons per km². Annual growth runs ~0.78% early, easing to ~0.55%, among the slowest in the panel.`,
      `The district is heavily tribal, Saora (Lanjia and Sudda), Kondh and other communities make up over 50% of the population, and forest economy dominates rural livelihood. Mahendragiri (1,501 m) is the highest peak in Odisha. Paralakhemundi (district HQ) was historically the seat of the princely Gajapati dynasty and retains a small heritage tourism flow.`,
      `Urbanisation rises from 11.46% to 15.71%. Urban population grows from ~66,000 to ~107,000; rural grows by ~60,000. Service-delivery priorities are tribal-area health and education (particularly for Saora populations), forest-fringe livelihoods, and connectivity through difficult terrain.`,
    ],
    highlightPhrases: [
      '~0.78%',
      '~0.55%',
      '4,325 km²',
      '157 persons per km²',
      '000 by 2036',
      '578,000',
      '678,000',
      '100,000',
      '134',
      '50%',
      '1,501',
      '11.46%',
      '15.71%',
      '~66,000',
      '~107,000',
      '~60,000',
    ],
  },

  Ganjam: {
    paragraphs: [
      `Ganjam is the most populous district in Odisha. Population grows from 3.53 million in 2011 to 4.15 million by 2036, the largest absolute increment in the state (~625,000) at a modest CAGR of 0.65%. Across 8,206 km², density rises from 430 to 506 persons per km².`,
      `Coastal southern Odisha, the district anchors the Berhampur urban region (Odisha's third-largest city) with the MKCG Medical College, Berhampur University, the IIT–IISER feeder ecosystem, and a sizeable cashew-and-fish industrial base. The Chhatrapur–Gopalpur port-tourism corridor and Chilika Lake (part of which falls in Ganjam) provide additional economic anchors. Ganjam has had one of the earliest fertility transitions in Odisha, a reason its growth rate sits in the lower middle of the panel despite the absolute scale.`,
      `Urbanisation moves from 21.42% in 2011 to 25.67% by 2036, well above the state mean. Urban population grows from ~756,000 to ~1.07 million, an increment of 310,000; rural from 2.77 million to 3.09 million. The Berhampur metropolitan corridor and the Chhatrapur–Gopalpur belt absorb most urban growth.`,
      `The planning frame here is closer to Cuttack than to the tribal interior: secondary-city infrastructure, port-cluster spillovers, and cyclone-resilient coastal services.`,
    ],
    highlightPhrases: [
      '3.53 million',
      '4.15 million',
      '0.65%',
      '8,206 km²',
      '506 persons per km²',
      '~625,000',
      '430',
      '~1.07 million',
      '2.77 million',
      '3.09 million',
      '21.42%',
      '25.67% by 2036',
      '~756,000',
      '310,000',
    ],
  },

  Jagatsinghapur: {
    paragraphs: [
      `Jagatsinghpur is the smallest district by land area in this panel at 1,668 km² but carries one of the highest densities: 682 persons per km² in 2011 rising to 797 by 2036. Population grows from 1.14 million to 1.33 million, an addition of 193,000 at CAGR 0.63%. Annual growth runs ~0.73% early, easing to ~0.57%.`,
      `The district hosts Paradip Port, India's largest seaport by cargo volume, the IOCL Paradip Refinery (15 MTPA), and a downstream petrochemical and fertilizer cluster (IFFCO, PPL). It was also the proposed POSCO Steel site between 2005–2017. Despite this industrial footprint, agriculture (paddy, betel-vine, fish) remains the dominant rural employer.`,
      `Urbanisation moves from 11.06% to 15.31%. Urban population grows from ~126,000 to ~204,000, with most increment in the Paradip–Naugaon belt and Jagatsinghpur town. Rural population still grows by 115,000. The strategic frame is port-and-petrochemical corridor management: industrial-cluster environment, peri-urban Paradip housing, and cyclone resilience.`,
    ],
    highlightPhrases: [
      '1.14 million',
      '1.33 million',
      '0.63%',
      '~0.73%',
      '~0.57%',
      '1,668 km²',
      '682 persons per km²',
      '797 by 2036',
      '193,000',
      '11.06%',
      '15.31%',
      '~126,000',
      '~204,000',
      '115,000',
    ],
  },

  Jajapur: {
    paragraphs: [
      `Jajpur grows from 1.83 million in 2011 to 2.15 million by 2036, an increase of 325,000, substantial for its 2,899 km² area. Density rises from 630 to 743 persons per km², among the higher coastal densities. Annual growth runs ~0.77% early, easing to ~0.59%.`,
      `The district hosts the Kalinga Nagar Industrial Complex, Tata Steel Long Products (the former NINL), Visa Steel, MESCO Steel, and Jindal Stainless ferrochrome, making it one of Odisha's most concentrated steel-and-ferrochrome clusters. Beyond industry, Buddhist heritage (Lalitgiri, Ratnagiri, Udayagiri, the "Diamond Triangle") and the Sukinda chromite belt anchor the district.`,
      `Urbanisation moves modestly from 7.43% to 11.68%. Urban population grows from ~136,000 to ~251,000, a 116,000 absolute increment, mostly in the Vyasanagar–Sukinda industrial corridor and Jajpur town. Rural population still grows by 210,000. Strategic priorities: chromite-mining environmental remediation (the Sukinda valley is among India's most polluted hot-spots), worker-housing around the steel cluster, and Buddhist heritage tourism.`,
    ],
    highlightPhrases: [
      '1.83 million',
      '2.15 million',
      '~0.77%',
      '~0.59%',
      '2,899 km²',
      '743 persons per km²',
      '325,000',
      '630',
      '7.43%',
      '11.68%',
      '~136,000',
      '~251,000',
      '116,000',
      '210,000',
    ],
  },

  Jharsuguda: {
    paragraphs: [
      `Jharsuguda has the highest urban share of any district outside Khordha. Population grows from 580,000 in 2011 to 683,000 by 2036, an increase of 104,000. Across only 2,114 km², density rises from 274 to 323 persons per km². Annual growth runs ~0.81% early, easing to ~0.57%.`,
      `The district is industrial: MCL's Lakhanpur coal mines, Vedanta Aluminium (one of India's largest smelters), Vedanta–Sterlite captive power plants, and the strategic Howrah–Mumbai railway junction at Jharsuguda. The Veer Surendra Sai Airport at Jharsuguda is Odisha's second commercial airport. The 40% urban share already in 2011 reflects the company-town heritage.`,
      `Urbanisation moves from 40.32% in 2011 to 44.57% by 2036, close to flat on a percentage basis, because the baseline is already high. Urban population grows from ~234,000 to ~305,000, increment of 71,000; rural by ~33,000.`,
      `Planning priorities are industrial-cluster air-quality and water management, rail-freight corridor logistics, and the integration of Jharsuguda town and Brajarajnagar into a coherent urban service area.`,
    ],
    highlightPhrases: [
      '~0.81%',
      '~0.57%',
      '2,114 km²',
      '323 persons per km²',
      '000 by 2036',
      '580,000',
      '683,000',
      '104,000',
      '274',
      '40%',
      '40.32%',
      '44.57% by 2036',
      '~234,000',
      '~305,000',
      '71,000',
      '~33,000',
    ],
  },

  Kalahandi: {
    paragraphs: [
      `Kalahandi grows from 1.58 million in 2011 to 1.85 million by 2036, an increase of 278,000. Across 7,920 km², density rises from 199 to 234 persons per km². Annual growth runs ~0.78% early, easing to ~0.58%.`,
      `Once nationally synonymous with drought and rural distress, Kalahandi today has a more mixed profile: NREGS coverage, irrigation expansion, and bauxite mining (Vedanta's Lanjigarh alumina refinery, long-contested over tribal Dongria Kondh displacement at Niyamgiri) have all shaped its trajectory since 2011. Bhawanipatna is the HQ; Junagarh and Dharamgarh are sub-centres. Scheduled Tribe population is over 28%.`,
      `Urbanisation moves from 7.61% in 2011 to 11.86% by 2036. Urban population grows from ~120,000 to ~220,000, relatively large for the baseline. Rural population grows by 178,000. Strategic priorities are irrigation completion (Indravati and Upper Indravati), bauxite-extraction governance and tribal-area consultation, and small-town infrastructure for Bhawanipatna–Junagarh.`,
    ],
    highlightPhrases: [
      '1.58 million',
      '1.85 million',
      '~0.78%',
      '~0.58%',
      '7,920 km²',
      '234 persons per km²',
      '278,000',
      '199',
      '28%',
      '7.61%',
      '11.86% by 2036',
      '~120,000',
      '~220,000',
      '178,000',
    ],
  },

  Kandhamal: {
    paragraphs: [
      `Kandhamal has the lowest population density in Odisha: 91 persons per km² in 2011 rising to 110 by 2036. Population grows from 733,000 to 881,000 over the period, an increment of 148,000 at CAGR 0.74%, on the higher end of the panel. Annual growth runs ~0.87% early, easing to ~0.66%.`,
      `The district is hilly, predominantly tribal (Kondha–Kui language area, also called Kandha; over 53% ST), with over 56% of land under forest cover. Turmeric cultivation in the Daringbadi–G. Udayagiri belt is a distinctive economic feature; coffee plantations and herbal-product co-ops have emerged in pockets. Kandhamal is also known for the 2008 communal violence, which left a lasting impact on inter-community trust in some blocks.`,
      `Urbanisation rises from 7.41% in 2011 to 11.66% by 2036. Urban population grows from ~54,000 to ~103,000, concentrated in Phulbani (HQ) and G. Udayagiri. Rural population still grows by 100,000. Service-delivery priorities are tribal health and education, forest-product value chains (turmeric, coffee), and conflict-sensitive development planning.`,
    ],
    highlightPhrases: [
      '0.74%',
      '~0.87%',
      '~0.66%',
      '91 persons per km²',
      '110 by 2036',
      '733,000',
      '881,000',
      '148,000',
      '53%',
      '56%',
      '7.41%',
      '11.66% by 2036',
      '~54,000',
      '~103,000',
      '100,000',
    ],
  },

  Kendrapara: {
    paragraphs: [
      `Kendrapara grows from 1.44 million in 2011 to 1.69 million by 2036, an increase of 251,000. Across 2,644 km², density rises from 545 to 640 persons per km². Annual growth runs ~0.74% early, easing to ~0.60%.`,
      `Coastal central Odisha, the district hosts Bhitarkanika National Park, India's second-largest mangrove ecosystem after the Sundarbans, and a critical saltwater crocodile habitat. Beyond mangroves, the economy is paddy agriculture, brackish-water prawn farming (which has expanded substantially since 2011), and traditional fisheries. The district is highly exposed to cyclones, Fani (2019) and Yaas (2021) caused significant damage.`,
      `Urbanisation rises from 4.69%, the lowest in the state in 2011, to 8.94% by 2036. Urban population grows from ~68,000 to ~151,000, more than doubling. Rural population still grows by 167,000. Strategic priorities are mangrove conservation and ecosystem-services-based livelihoods, cyclone-resilient housing, brackish-water aquaculture regulation, and Kendrapara town infrastructure.`,
    ],
    highlightPhrases: [
      '1.44 million',
      '1.69 million',
      '~0.74%',
      '~0.60%',
      '2,644 km²',
      '640 persons per km²',
      '251,000',
      '545',
      '4.69%',
      '8.94% by 2036',
      '~68,000',
      '~151,000',
      '167,000',
    ],
  },

  Kendujhar: {
    paragraphs: [
      `Kendujhar (Keonjhar) grows from 1.80 million in 2011 to 2.17 million by 2036, a 372,000-person increase over 8,303 km² of largely undulating terrain. Density rises from 217 to 262 persons per km². Annual growth peaks early at ~0.86% before declining gradually, typical of mining belts where in-migration moderates as extraction industries mature.`,
      `The district is one of India's largest iron-ore producers and also yields manganese, with Joda, Barbil and Champua hosting most mining activity. Historical population growth in Kendujhar has been higher than the state average due to mining-led migration, but the projection captures a normalisation as remote-employment dynamics catch up with declining household size. The substantial Scheduled Tribe share, over 45% of the district total per Census 2011, keeps fertility patterns somewhat above the urban-corridor districts.`,
      `Urbanisation moves from 13.37% in 2011 to 17.62% by 2036, still well below the state mean. Urban population grows from ~241,000 to ~383,000, with most of the increment accruing in the Barbil–Joda mining-town complex and Kendujhar town itself. Rural population continues to grow in absolute terms, a contrast with several neighbouring districts where rural counts have begun to flatten.`,
      `Planning priorities therefore span mining-town water and air-quality services, post-mining land transition once iron-ore reserves deplete, and infrastructure for the predominantly tribal rural majority.`,
    ],
    highlightPhrases: [
      '1.80 million',
      '2.17 million',
      '~0.86%',
      '8,303 km²',
      '262 persons per km²',
      '372,000',
      '217',
      '45%',
      '13.37%',
      '17.62% by 2036',
      '~241,000',
      '~383,000',
    ],
  },

  Khordha: {
    paragraphs: [
      `Khordha is the most urbanised district in Odisha and contains the state capital Bhubaneswar. Population grows from 2.25 million in 2011 to 2.66 million by 2036, an absolute increase of roughly 411,000. With only 2,888 km², by far the smallest area among the populous districts, density is exceptional: 780 persons per km² in 2011, rising to 922 by 2036, almost three times the state average.`,
      `Year-on-year growth runs around 0.8% early in the period, slowing to ~0.55% by the early 2030s. That slowdown reflects a pattern visible in many Tier-II Indian capitals: rapid expansion in the 2000s gives way to steadier, services-driven growth as the city's catchment for in-migration shifts from rural Odisha to inter-state professionals.`,
      `Urbanisation already dominates. The Census 2011 urban share of 48.13% rises to about 52.38% by 2036, Khordha is the only district where urban population overtakes rural by 2030. Urban headcount climbs from ~1.08 million to ~1.40 million; rural population stays roughly flat in absolute terms, around 1.17–1.27 million. Bhubaneswar's IT corridor, the Khordha industrial belt, and the Patia–Tomando peri-urban expansion absorb most of the increment.`,
      `The strategic frame for Khordha is metropolitan, not district-rural: master-plan-led infill, transit-oriented development, and BMC–Khordha coordination on water sourcing and waste handling.`,
    ],
    highlightPhrases: [
      '2.25 million',
      '2.66 million',
      '2,888 km²',
      '780 persons per km²',
      '922 by 2036',
      '411,000',
      '0.8%',
      '~0.55%',
      '~1.08 million',
      '~1.40 million',
      '1.27 million',
      '48.13%',
      '52.38% by 2036',
    ],
  },

  Koraput: {
    paragraphs: [
      `Koraput grows from 1.38 million in 2011 to 1.62 million by 2036, an increase of 244,000. Across 8,807 km² of plateau terrain, density rises from 157 to 184 persons per km². Annual growth runs ~0.78% early, easing to ~0.58%.`,
      `Despite a tribal-rural majority, Bhumia, Paroja, Kondha and other communities together over 50%, Koraput has an unusually diverse industrial-and-institutional base for the southern belt: NALCO's Damanjodi alumina refinery, HAL's Sunabeda MIG facility, ITER engineering colleges, and the Central University of Odisha at Sunabeda. The Sunabeda plateau also hosts a wildlife sanctuary. Jeypore is the largest urban centre, with Koraput town as HQ.`,
      `Urbanisation moves from 16.93% to 21.18%, higher than most southern districts. Urban population grows from ~234,000 to ~344,000; rural by 134,000. Strategic priorities are tribal-area health, education and connectivity in the rural majority; industrial-corridor management around NALCO; and the Jeypore–Sunabeda urban cluster.`,
    ],
    highlightPhrases: [
      '1.38 million',
      '1.62 million',
      '~0.78%',
      '~0.58%',
      '8,807 km²',
      '184 persons per km²',
      '244,000',
      '157',
      '50%',
      '16.93%',
      '21.18%',
      '~234,000',
      '~344,000',
      '134,000',
    ],
  },

  Malkangiri: {
    paragraphs: [
      `Malkangiri grows from 613,000 in 2011 to 731,000 by 2036, an addition of 118,000. Across 5,791 km² of forest-and-plateau terrain, density rises from 106 to 126 persons per km², among the lowest in the state. Annual growth runs ~0.79% early, easing to ~0.66%.`,
      `Odisha's southernmost district, bordering Andhra Pradesh and Chhattisgarh, Malkangiri is predominantly tribal, Bondo, Koya and Didayi communities (the first two classified as Particularly Vulnerable Tribal Groups) have significant presence. Forest cover exceeds 56% of area. The district was a Maoist-affected zone through the 2000s and early 2010s; security and development indicators have both improved markedly. The Balimela hydroelectric project on the Sileru river is the largest infrastructure asset.`,
      `Urbanisation rises from 7.61% to 11.86%. Urban population grows from ~47,000 to ~87,000, with most increment in Malkangiri town (HQ) and Motu. Rural population still grows by ~78,000. Service-delivery priorities are PVTG welfare, last-mile connectivity, post-Maoist reintegration support, and small-town infrastructure.`,
    ],
    highlightPhrases: [
      '~0.79%',
      '~0.66%',
      '5,791 km²',
      '126 persons per km²',
      '000 by 2036',
      '613,000',
      '731,000',
      '118,000',
      '106',
      '56%',
      '7.61%',
      '11.86%',
      '~47,000',
      '~87,000',
      '~78,000',
    ],
  },

  Mayurbhanj: {
    paragraphs: [
      `Mayurbhanj is the largest district in Odisha by area (10,418 km²) and the second-largest in the panel by population. Total residents rise from 2.52 million in 2011 to 3.02 million by 2036, a gain of about 499,000. Density nonetheless remains among the lowest in the panel, 242 persons per km² in 2011, reaching 290 by 2036, reflecting the dispersed settlement pattern and the Similipal Biosphere Reserve, which occupies a large protected core.`,
      `Year-on-year growth runs ~0.85% in the early years, easing to ~0.65% in the 2030s. The district's tribal share, over 58%, the largest absolute Scheduled Tribe population of any single Indian district, and forest-dependent rural economy keep fertility moderately above the state mean and out-migration limited. Iron-ore extraction in the Suleipat and Badampahar areas is small relative to Kendujhar but provides modest non-agrarian employment.`,
      `Urbanisation is the lowest of the panel: 7.78% in 2011 climbing to 12.03% by 2036. Urban population grows from ~196,000 to ~363,000, concentrated in Baripada (HQ), Rairangpur and Karanjia. Rural population still adds the bulk of new residents in absolute terms, roughly 332,000 over the period.`,
      `Service-delivery priorities here are tribal-area health and education, forest-fringe livelihoods, and last-mile connectivity rather than urban-system planning. The district is large enough that within-district disparities (Baripada vs. Similipal-fringe blocks) typically dominate over the district aggregate.`,
    ],
    highlightPhrases: [
      '2.52 million',
      '3.02 million',
      '10,418 km²',
      '242 persons per km²',
      '290 by 2036',
      '499,000',
      '~0.85%',
      '~0.65%',
      '58%',
      '7.78%',
      '12.03% by 2036',
      '~196,000',
      '~363,000',
      '332,000',
    ],
  },

  Nabarangpur: {
    paragraphs: [
      `Nabarangpur has the highest Scheduled Tribe percentage of any Odisha district, over 55% of population is tribal, primarily Bhattra, Bhumia, Gond and Halba. Population grows from 1.22 million in 2011 to 1.46 million by 2036, an addition of 242,000. Across 5,294 km², density rises from 231 to 276 persons per km². Annual growth runs ~0.85% early, easing to ~0.65%.`,
      `Part of the KBK (Koraput–Bolangir–Kalahandi) historically-disadvantaged belt, Nabarangpur depends on agriculture (paddy, maize, finger millet), forest produce and labour-migration cycles to Andhra Pradesh and Maharashtra. The Indravati hydroelectric project and Upper Indravati reservoir occupy the southern portion of the district. Nabarangpur town and Umerkote are the principal urban centres.`,
      `Urbanisation moves from 7.17% to 11.42% over the period. Urban population grows from ~88,000 to ~167,000, almost doubling in absolute terms, though still modest. Rural population still grows by 162,000. Strategic priorities are tribal-area health and nutrition (PVTG components, infant-mortality reduction), millet-and-pulses agriculture support, and last-mile connectivity through the Indravati submergence zone.`,
    ],
    highlightPhrases: [
      '1.22 million',
      '1.46 million',
      '55%',
      '~0.85%',
      '~0.65%',
      '5,294 km²',
      '276 persons per km²',
      '242,000',
      '231',
      '7.17%',
      '11.42%',
      '~88,000',
      '~167,000',
      '162,000',
    ],
  },

  Nayagarh: {
    paragraphs: [
      `Nayagarh grows from 963,000 in 2011 to 1.14 million by 2036, an addition of 179,000. Across 3,890 km², density rises from 248 to 294 persons per km². Annual growth runs ~0.83% early, easing to ~0.60%.`,
      `Central Odisha just south-west of the Bhubaneswar metropolitan region, Nayagarh combines a horticulture economy (turmeric, spinach, jhana orange) with growing peri-urban influence from Khordha. The district shares the Mahanadi River with Cuttack and the Satkosia gorge wildlife sanctuary with Anugul. Daspalla and Nayagarh town are the principal urban centres.`,
      `Urbanisation rises from 4.40%, the lowest in Odisha in 2011, to 8.65% by 2036. Urban population almost triples from ~42,000 to ~99,000; rural still grows by 122,000. Strategic priorities are horticulture value-chains, water-supply augmentation as Bhubaneswar's southern peripheries press into the district, and Khordha–Nayagarh corridor planning.`,
    ],
    highlightPhrases: [
      '1.14 million',
      '~0.83%',
      '~0.60%',
      '3,890 km²',
      '294 persons per km²',
      '963,000',
      '179,000',
      '248',
      '4.40%',
      '8.65% by 2036',
      '~42,000',
      '~99,000',
      '122,000',
    ],
  },

  Nuapada: {
    paragraphs: [
      `Nuapada grows from 610,000 in 2011 to 722,000 by 2036, an addition of 112,000. Across 3,852 km², density rises from 158 to 188 persons per km². Annual growth runs ~0.80% early, easing to ~0.60%.`,
      `Western Odisha's KBK frontier, bordering Chhattisgarh, Nuapada was carved from Kalahandi in 1993. The economy is agriculture-and-forest based, with persistent drought vulnerability driving seasonal labour migration to Chhattisgarh and Andhra Pradesh. The district has a substantial Scheduled Tribe share and is bordered by tribal-majority districts on multiple sides. Khariar Road and Nuapada town anchor the small urban network.`,
      `Urbanisation rises from 5.59% in 2011 to 9.84% by 2036. Urban population grows from ~34,000 to ~71,000, more than doubling. Rural population still grows by 75,000. Strategic priorities are drought-management infrastructure (rainwater harvesting, watershed development), migration-management for seasonal workers, and small-town governance capacity.`,
    ],
    highlightPhrases: [
      '~0.80%',
      '~0.60%',
      '3,852 km²',
      '188 persons per km²',
      '000 by 2036',
      '610,000',
      '722,000',
      '112,000',
      '158',
      '5.59%',
      '9.84% by 2036',
      '~34,000',
      '~71,000',
      '75,000',
    ],
  },

  Puri: {
    paragraphs: [
      `Puri's population grows from 1.70 million in 2011 to 1.98 million by 2036, an addition of 280,000. Across 3,479 km², density rises from 488 to 569 persons per km². Annual growth runs ~0.71% early, easing to ~0.56%, the slowest CAGR of any district in this panel at 0.61%, reflecting Puri's near-completed demographic transition.`,
      `Coastal Odisha's tourism and pilgrimage anchor: Puri town hosts the Jagannath Temple (one of the Char Dham of Hindu pilgrimage), Konark Sun Temple is in adjoining Khurda but within the cultural region, and Puri Beach is among India's most-visited. The district was selected as a Smart City and has invested heavily in pilgrimage infrastructure post-Fani (2019). The Chilika Lake portion, Sakhigopal heritage, and the artisan/sand-art ecosystem provide additional cultural-economy depth.`,
      `Urbanisation moves from 16.30% to 20.55%. Urban population grows from ~277,000 to ~407,000, most in Puri town and the temple corridor. Rural population grows by 150,000. Strategic priorities are religious-tourism carrying capacity, beach-erosion and cyclone resilience (Puri is one of the most exposed Indian shorelines), heritage conservation in the temple precinct, and water-and-sanitation augmentation for peak-season loads.`,
    ],
    highlightPhrases: [
      '1.70 million',
      '1.98 million',
      '~0.71%',
      '~0.56%',
      '0.61%',
      '3,479 km²',
      '569 persons per km²',
      '280,000',
      '488',
      '16.30%',
      '20.55%',
      '~277,000',
      '~407,000',
      '150,000',
    ],
  },

  Rayagada: {
    paragraphs: [
      `Rayagada grows from 968,000 in 2011 to 1.14 million by 2036, an addition of 171,000. Across 7,073 km², density rises from 137 to 161 persons per km². Annual growth runs ~0.80% early, easing to ~0.56%.`,
      `Southern tribal Odisha, the district hosts JK Paper Mill at Rayagada, NALCO captive bauxite mining, and Vedanta refinery operations at Lanjigarh straddle the Kalahandi–Rayagada border. Kondha and Soura communities are dominant tribal groups; the Niyamgiri hill range, sacred to the Dongria Kondh, is partially within the district and has been at the centre of one of India's most-studied indigenous-rights mobilisations. Gunpur is the secondary urban centre.`,
      `Urbanisation moves from 16.36% to 20.61%, higher than most southern districts. Urban population grows from ~158,000 to ~235,000; rural by 95,000. Strategic priorities are tribal-consent processes for resource extraction (the Niyamgiri precedent), watershed and forest management, paper-mill effluent governance, and Rayagada–Gunpur urban-services capacity.`,
    ],
    highlightPhrases: [
      '1.14 million',
      '~0.80%',
      '~0.56%',
      '7,073 km²',
      '161 persons per km²',
      '968,000',
      '171,000',
      '137',
      '16.36%',
      '20.61%',
      '~158,000',
      '~235,000',
      '95,000',
    ],
  },

  Sambalpur: {
    paragraphs: [
      `Sambalpur, with the smallest population in the original 8-district panel, grows from 1.04 million in 2011 to 1.23 million by 2036, about 194,000 additional residents. The 6,624 km² land area gives a low density: 157 persons per km² in 2011, climbing to 186 in 2036, well below the state average.`,
      `Annual growth runs around 0.83% in the early years and slows to about 0.61% by the early 2030s. Sambalpur's economy combines the Hirakud Dam–irrigation footprint, a notable higher-education cluster (Sambalpur University, VSSUT Burla, IIM Sambalpur), small-scale industry, and trade serving western Odisha. Distinctively, it carries one of the highest urban shares among non-coastal districts, 31.01% in 2011, projected to reach 35.26% by 2036, driven by the Sambalpur–Burla–Hirakud agglomeration.`,
      `Urban population grows from ~323,000 to ~436,000, an increase of about 113,000 over 25 years. Rural population grows more slowly (about 80,000 net), continuing the trajectory visible since the 2001 Census. The Hirakud reservoir and surrounding forest tracts limit physical expansion northward, so most growth concentrates along the NH-53 corridor and around the educational institutions.`,
      `Strategic emphases consistent with this trajectory are urban-cluster water and sanitation, university-town economy, and conservation-compatible peripheral growth around Hirakud.`,
    ],
    highlightPhrases: [
      '1.04 million',
      '1.23 million',
      '6,624 km²',
      '157 persons per km²',
      '194,000',
      '186',
      '0.83%',
      '0.61%',
      '31.01%',
      '35.26% by 2036',
      '~323,000',
      '~436,000',
      '113,000',
      '80,000',
    ],
  },

  Sonepur: {
    paragraphs: [
      `Subarnapur (Sonepur) grows from 610,000 in 2011 to 716,000 by 2036, an addition of 106,000. The 2,337 km² area gives density of 261 rising to 307 persons per km². Annual growth runs ~0.76% early, easing to ~0.57%.`,
      `Western Odisha, at the confluence of the Mahanadi and Tel rivers, Subarnapur was carved from Balangir in 1993. The district is the historic centre of the Sambalpuri handloom tradition, Sonepur town's tie-dye (ikat) weaving has GI registration and supplies a substantial proportion of branded Sambalpuri sari output. Agriculture (paddy, irrigation from Hirakud canal extensions) and weaving together anchor the rural economy.`,
      `Urbanisation rises from 6.74% in 2011 to 10.99% by 2036. Urban population grows from ~41,000 to ~79,000; rural by 69,000. Strategic priorities are handloom-cluster modernisation and GI-protected value-chain development, river-confluence flood management, and Sonepur town infrastructure (the district is small enough that one urban centre dominates).`,
    ],
    highlightPhrases: [
      '~0.76%',
      '~0.57%',
      '2,337 km²',
      '307 persons per km²',
      '000 by 2036',
      '610,000',
      '716,000',
      '106,000',
      '261',
      '6.74%',
      '10.99% by 2036',
      '~41,000',
      '~79,000',
      '69,000',
    ],
  },

  Sundargarh: {
    paragraphs: [
      `Sundargarh's population grows from 2.09 million in 2011 to 2.49 million by 2036, an increase of about 400,000. The 9,712 km² area, second-largest in the state by area, keeps density moderate: 215 persons per km² in 2011, reaching 257 by 2036.`,
      `Year-on-year growth runs ~0.81% early, easing to ~0.59% in the 2030s. The district hosts SAIL's Rourkela Steel Plant, one of India's earliest public-sector steel facilities, alongside iron-ore and manganese mining clusters at Bonai and Birmitrapur. Rourkela itself is a Smart City and the district's largest urban centre, the only town in non-coastal Odisha approaching half-a-million population. The combined pull of steel, mining and rail-junction economies sustains in-migration; tribal communities (over 50% of district total per Census 2011) form a counterweight in the rural blocks.`,
      `Urbanisation is the second-highest in the panel: from 35.34% in 2011 to 39.59% by 2036. Urban population grows from ~740,000 to ~987,000, extending Rourkela's metropolitan footprint into adjoining peri-urban tracts. Rural population grows more slowly, by about 153,000 over 25 years, concentrated in the tribal blocks of Bonai, Lephripara and Sundargarh sadar.`,
      `Sundargarh sits at the intersection of industrial-corridor and tribal-belt planning: steel-and-mining environment management, peri-urban Rourkela infrastructure, and tribal-block service delivery. Its trajectory more closely resembles Jamshedpur (Jharkhand) than the rest of Odisha, despite the political boundary.`,
    ],
    highlightPhrases: [
      '2.09 million',
      '2.49 million',
      '9,712 km²',
      '215 persons per km²',
      '257 by 2036',
      '400,000',
      '~0.81%',
      '~0.59%',
      '50%',
      '35.34%',
      '39.59% by 2036',
      '~740,000',
      '~987,000',
      '153,000',
    ],
  },

};